import type { Metadata } from "next";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import React from 'react';

import { ConfigProvider, } from 'antd';
import { Roboto } from 'next/font/google';

import "./globals.css";
import "@/src/styles/styles.scss";

const roboto = Roboto({
  weight: ['400', "700"],
  subsets: ['latin'],
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Real Estate",
  description: "Generated by Muneeb",
};


const colorPrimary = "#ac46ff";
const colorInfo = "#ac46ff";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AntdRegistry>
          <ConfigProvider
            theme={{
              "token": {
                colorPrimary,
                colorInfo,
              }
            }}>
            {children}
          </ConfigProvider>
        </AntdRegistry>

      </body>
    </html>
  );
}
